### ISSUE TITLE
Docker: connection failure from inside a container under certain circumstances

### ISSUE THREAD

**Issue by cswgr** [genotrance/px#100]
I set up Px Proxy behind our company proxy and it works okay with all my programs I have installed in **Windows 10**.
Docker itself is able to use Px Proxy to pull images, so that's okay, too.

Trouble is, when I'm building a container, and I'm trying to use `apt-get`, I'm getting this error:

```log
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim-runtime_8.0.1453-1ubuntu1.1_all.deb  Connection failed [IP: 192.168.65.2 3128]
```

Here is a complete example:

Using this simple Dockerfile, which I run with docker-compose:

```dockerfile
FROM selenium/node-chrome-debug:3

USER root

RUN apt-get update ; \
    apt-get install -y --allow-unauthenticated \
    vim \
    less
```

The output is this:

```log
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe "docker-compose up -d"
Step 1/3 : FROM selenium/node-chrome-debug:3
 ---> 8a5b08cf9525
Step 2/3 : USER root
 ---> Using cache
 ---> dac2511b6f24
Step 3/3 : RUN apt-get update ;     apt-get install -y --allow-unauthenticated     vim     less
 ---> Running in 236621c5b3fa
docker-compose : Building selenium_chrome_1
In Zeile:1 Zeichen:1
+ docker-compose up -d
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Building selenium_chrome_1:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [794 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [760 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,056 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,322 kB]
Fetched 17.0 MB in 5s (3,400 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libgpm2 libpython3.6 libpython3.6-minimal libpython3.6-stdlib python3.6
  python3.6-minimal vim-common vim-runtime xxd
Suggested packages:
  gpm python3.6-venv python3.6-doc binutils binfmt-support ctags vim-doc
  vim-scripts
The following NEW packages will be installed:
  less libgpm2 libpython3.6 vim vim-common vim-runtime xxd
The following packages will be upgraded:
  libpython3.6-minimal libpython3.6-stdlib python3.6 python3.6-minimal
4 upgraded, 7 newly installed, 0 to remove and 33 not upgraded.
Need to get 12.3 MB of archives.
After this operation, 37.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6 amd64 3.6.9-1~18.04 [203 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-stdlib amd64 3.6.9-1~18.04 [1,709 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6-minimal amd64 3.6.9-1~18.04 [1,610 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-minimal amd64 3.6.9-1~18.04 [533 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 less amd64 487-0.1 [112 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 xxd amd64 2:8.0.1453-1ubuntu1.1 [49.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 vim-common all 2:8.0.1453-1ubuntu1.1 [70.4 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgpm2 amd64 1.20.7-5 [15.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6 amd64 3.6.9-1~18.04 [1,414 kB]
Ign:10 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 vim-runtime all 2:8.0.1453-1ubuntu1.1
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 vim amd64 2:8.0.1453-1ubuntu1.1 [1,152 kB]
Err:10 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 vim-runtime all 2:8.0.1453-1ubuntu1.1
  Connection failed [IP: 192.168.65.2 3128]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim-runtime_8.0.1453-1ubuntu1.1_all.deb  Connection failed [IP: 192.168.65.2 3128]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 6,867 kB in 2min 22s (48.3 kB/s)
Service 'selenium_chrome_1' failed to build: The command '/bin/sh -c apt-get update ;     apt-get install -y
--allow-unauthenticated     vim     less' returned a non-zero code: 100

Process finished with exit code 1

```
As you can see, it downloads some packages, but then it seems to get stuck for a while, then outputs the error mentioned above.

It happens _almost_ every time, sometimes it works if I restart Px Proxy.

Using Cntlm (which I'm trying to get rid of) everything works fine.

Does anybody know what's wrong?

**Comment by cswgr** [comment]
Forgot to mention my `px.ini`:

```ini
[proxy]
server = company.proxy.com:8080
pac = 
port = 3128
listen = 127.0.0.1
allow = *.*.*.*
gateway = 0
hostonly = 1
noproxy = 
useragent = 
username = me
auth = NTLM

[settings]
workers = 2
threads = 5
idle = 30
socktimeout = 30.0
proxyreload = 60
foreground = 0
log = 0
```

**Comment by genotrance** [comment]
Can you capture and share the px debug log? It might offer some clues.

**Comment by cswgr** [comment]
Tried to reproduce it with another project, which fails to connect to `http://cdn-fastly.deb.debian.org/debian/pool/main/v/vim/vim-runtime_8.1.0875-5_all.deb` during the build process.
In the (very long) log I have this at the end:

```log
MainProcess: Thread_1: 1576049902: do_GET: Path = http://cdn-fastly.deb.debian.org/debian/pool/main/v/vim/vim-runtime_8.1.0875-5_all.deb
MainProcess: Thread_1: 1576049902: do_transaction: Entering
MainProcess: Thread_1: 1576049902: get_destination: cdn-fastly.deb.debian.org:80
MainProcess: Thread_1: 1576049902: get_response_sspi: pywin32 SSPI
MainProcess: Thread_1: 1576049902: fwd_data: Reading response data
MainProcess: Thread_1: 1576049902: do_socket: Entering
MainProcess: Thread_1: 1576049902: do_socket: GET http://cdn-fastly.deb.debian.org/debian/pool/main/v/vim/vim-runtime_8.1.0875-5_all.deb HTTP/1.1
MainProcess: Thread_1: 1576049902: do_socket: Sending Host: cdn-fastly.deb.debian.org
MainProcess: Thread_1: 1576049902: do_socket: Sending User-Agent: Debian APT-HTTP/1.3 (1.8.2)
MainProcess: Thread_1: 1576049902: do_socket: Sending extra Proxy-Authorization: sanitized len(77)
MainProcess: Thread_1: 1576049902: do_socket: Sending extra b'Proxy-Connection: Keep-Alive'
MainProcess: Thread_1: 1576049902: do_socket: Reading response code
MainProcess: Thread_1: 1576049902: do_socket: Response code: 407 True
MainProcess: Thread_1: 1576049902: do_socket: Reading response headers
MainProcess: Thread_1: 1576049902: do_socket: Received Via: 1.1 172.22.92.87 (McAfee Web Gateway)
MainProcess: Thread_1: 1576049902: do_socket: Received Date: Wed, 11 Dec 2019 07:38:22 GMT
MainProcess: Thread_1: 1576049902: do_socket: Received Content-Type: text/html
MainProcess: Thread_1: 1576049902: do_socket: Received Cache-Control: no-cache
MainProcess: Thread_1: 1576049902: do_socket: Received Content-Length: 0
MainProcess: Thread_1: 1576049902: do_socket: Received Proxy-Connection: Keep-Alive
MainProcess: Thread_1: 1576049902: do_socket: Received Proxy-Authenticate: sanitized (69)
MainProcess: Thread_1: 1576049902: do_transaction: Auth required
MainProcess: Thread_1: 1576049902: do_transaction: Challenged
MainProcess: Thread_1: 1576049902: get_response_sspi: pywin32 SSPI
MainProcess: Thread_1: 1576049902: fwd_data: Reading response data
MainProcess: Thread_1: 1576049902: do_socket: Entering
MainProcess: Thread_1: 1576049902: do_socket: GET http://cdn-fastly.deb.debian.org/debian/pool/main/v/vim/vim-runtime_8.1.0875-5_all.deb HTTP/1.1
MainProcess: Thread_1: 1576049902: do_socket: Sending Host: cdn-fastly.deb.debian.org
MainProcess: Thread_1: 1576049902: do_socket: Sending User-Agent: Debian APT-HTTP/1.3 (1.8.2)
MainProcess: Thread_1: 1576049902: do_socket: Sending extra Proxy-Authorization: sanitized len(377)
MainProcess: Thread_1: 1576049902: do_socket: Reading response code
MainProcess: Thread_1: 1576049913: do_socket: Response code: 200 True
MainProcess: Thread_1: 1576049913: do_socket: Reading response headers
MainProcess: Thread_1: 1576049913: do_socket: Received Age: 9353167
MainProcess: Thread_1: 1576049913: do_socket: Received via: Proxy
MainProcess: Thread_1: 1576049913: do_socket: Received Date: Mon, 25 Nov 2019 11:38:41 GMT
MainProcess: Thread_1: 1576049913: do_socket: Received ETag: "581d0c-58b60344b37f6"
MainProcess: Thread_1: 1576049913: do_socket: Received Server: Apache
MainProcess: Thread_1: 1576049913: do_socket: Received X-Cache: HIT, HIT, HIT from 172.22.92.87
MainProcess: Thread_1: 1576049913: do_socket: Received X-Timer: S1574681922.894609,VS0,VE0
MainProcess: Thread_1: 1576049913: do_socket: Received X-Served-By: cache-ams21036-AMS, cache-hhn4028-HHN
MainProcess: Thread_1: 1576049913: do_socket: Received Content-Type: application/x-debian-package
MainProcess: Thread_1: 1576049913: do_socket: Received X-Cache-Hits: 0, 0
MainProcess: Thread_1: 1576049913: do_socket: Received Accept-Ranges: bytes
MainProcess: Thread_1: 1576049913: do_socket: Received Accept-Ranges: bytes
MainProcess: Thread_1: 1576049913: do_socket: Received Cache-Control: public, max-age=2592000
MainProcess: Thread_1: 1576049913: do_socket: Received Last-Modified: Sat, 15 Jun 2019 17:36:34 GMT
MainProcess: Thread_1: 1576049913: do_socket: Received Content-Length: 5774604
MainProcess: Thread_1: 1576049913: do_socket: Received Referrer-Policy: no-referrer
MainProcess: Thread_1: 1576049913: do_socket: Received X-Frame-Options: sameorigin
MainProcess: Thread_1: 1576049913: do_socket: Received Proxy-Connection: Keep-Alive
MainProcess: Thread_1: 1576049913: do_socket: Received X-Xss-Protection: 1
MainProcess: Thread_1: 1576049913: do_socket: Received X-Clacks-Overhead: GNU Terry Pratchett
MainProcess: Thread_1: 1576049913: do_socket: Received X-Content-Type-Options: nosniff
MainProcess: Thread_1: 1576049913: fwd_resp: Entering
MainProcess: Thread_1: 1576049913: log_message: "GET http://cdn-fastly.deb.debian.org/debian/pool/main/v/vim/vim-runtime_8.1.0875-5_all.deb HTTP/1.1" 200 -
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Age: 9353167
MainProcess: Thread_1: 1576049913: fwd_resp: Returning via: Proxy
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Date: Mon, 25 Nov 2019 11:38:41 GMT
MainProcess: Thread_1: 1576049913: fwd_resp: Returning ETag: "581d0c-58b60344b37f6"
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Server: Apache
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Cache: HIT, HIT, HIT from 172.22.92.87
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Timer: S1574681922.894609,VS0,VE0
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Served-By: cache-ams21036-AMS, cache-hhn4028-HHN
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Content-Type: application/x-debian-package
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Cache-Hits: 0, 0
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Accept-Ranges: bytes
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Accept-Ranges: bytes
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Cache-Control: public, max-age=2592000
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Last-Modified: Sat, 15 Jun 2019 17:36:34 GMT
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Content-Length: 5774604
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Referrer-Policy: no-referrer
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Frame-Options: sameorigin
MainProcess: Thread_1: 1576049913: fwd_resp: Returning Proxy-Connection: Keep-Alive
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Xss-Protection: 1
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Clacks-Overhead: GNU Terry Pratchett
MainProcess: Thread_1: 1576049913: fwd_resp: Returning X-Content-Type-Options: nosniff
MainProcess: Thread_1: 1576049913: fwd_data: Reading response data
MainProcess: Thread_1: 1576049913: fwd_data: Content length 5774604
MainProcess: Thread_1: 1576049935: handle_one_request: Socket error: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
MainProcess: Thread_1: 1576049935: handle_one_request: Host disconnected
MainProcess: Thread_1: 1576049935: do_GET: Entering
MainProcess: Thread_1: 1576049935: do_GET: Path = http://cdn-fastly.deb.debian.org/debian/pool/main/v/vim/vim_8.1.0875-5_amd64.deb
MainProcess: Thread_1: 1576049935: do_transaction: Entering
MainProcess: Thread_1: 1576049935: get_destination: cdn-fastly.deb.debian.org:80
MainProcess: Thread_1: 1576049935: get_response_sspi: pywin32 SSPI
MainProcess: Thread_1: 1576049935: fwd_data: Reading response data
MainProcess: Thread_1: 1576049935: do_socket: Entering
MainProcess: Thread_1: 1576049935: do_socket: GET http://cdn-fastly.deb.debian.org/debian/pool/main/v/vim/vim_8.1.0875-5_amd64.deb HTTP/1.1
MainProcess: Thread_1: 1576049935: do_socket: Sending Host: cdn-fastly.deb.debian.org
MainProcess: Thread_1: 1576049935: do_socket: Sending User-Agent: Debian APT-HTTP/1.3 (1.8.2)
MainProcess: Thread_1: 1576049935: do_socket: Sending extra Proxy-Authorization: sanitized len(77)
MainProcess: Thread_1: 1576049935: do_socket: Sending extra b'Proxy-Connection: Keep-Alive'
MainProcess: Thread_1: 1576049935: do_socket: Reading response code
MainProcess: Thread_1: 1576049935: do_socket: Bad response b'\xbe\xf1M\xef-L\xa1\xfe\x11\x9du\x81\xda\xef6P\x7f\x01\xb9\xbd\x1bE"\x9c\xdd\x0c\x80\x9b\x04\xc5I\xfe\x11\xc7\x88\xfb\x8d]\x1f+\x7f\xba\xf9\xf8:\x136\xb8$6\x9bf\x1e\x17\x1a(\x0e\x1b:}\xbcc\xe6\xb9\xaa\x164\xbax\xdd\x90\xbd\xc5\xacLpH/\xd3n\x0b\x8f\xf7\xfc2\x8c\xafgf\xd649<\xb3~\xb5\x92\\\xda\x96\x889\x01\xd4\x13\xee_waC\x03v\xb3X\x10\xf0\x7f\x1e\xe97\x86\xf7\xa5<Al\x1b\xaeg\x04\x91\xd1\x93e!\xf3\xbc\xa9\xea#\xd4D\xb8V 6\xa9\xf3~\x8cQ\xc9\xe9\xbb\xf2\x9fY\xc2\xc7@>\x8d\xd71\xab\xc8L\xd8a\x0f|\x9bz\x07AX\x8b\xfa\xf29.\xbd\x96u\x1ep\\\xcc~\xa3\x07\xe4t\x05 HWWkrCe`8\xc1\xc0\x99o\xfc\xeb\x0e\x03\xbc9.\x9d-\x82\xa6\xf0\xbf:`2\x96\x14\xe8\xfa\x18\xfa\xab@=\x9fI\xa0#\xdf\x891\xe6\xb3\xf0J\xac\xc4\x9a\xfd$Q\xb8\xe1\x9bs4o\x93\x9f\x97\xcd!\x98\x81{\xcd\x8a\x11\x85\x15\xca\x13\xdd0\t\x12\xe2yNN\xc7y\xc9.G(\xec\xb6\x08Gn&\x14\xcf\xb4\xb4l\x84\x12l\xdc\xd2\xf1+\xb1\xb4A\xdb\xe2\x03\x97\xa2\xfd\xebA\x9bRV\xc4\'\xd7O\x17\xcd\r\xdd\x10\xc4\x04\xd4\xc9\x14\xf6v33B!\xf5\n'
MainProcess: Thread_1: 1576049935: do_socket: Response code: 503 True
MainProcess: Thread_1: 1576049935: do_socket: Reading response headers
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56985)
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 428, in handle
    self.handle_one_request()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\px_proxy-0.4.0-py3.8.egg\px.py", line 466, in handle_one_request
    httpserver.SimpleHTTPRequestHandler.handle_one_request(self)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\px_proxy-0.4.0-py3.8.egg\px.py", line 823, in do_GET
    resp = self.do_transaction()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\px_proxy-0.4.0-py3.8.egg\px.py", line 743, in do_transaction
    resp = self.do_socket({
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\px_proxy-0.4.0-py3.8.egg\px.py", line 624, in do_socket
    line = self.proxy_fp.readline(State.max_line).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 0: invalid continuation byte
----------------------------------------

```

**Comment by cswgr** [comment]
Problem still exists. Is this project maintained anyway?

**Comment by RunSeven** [comment]
Don't have a fix yet but may have a work around, setting the number of retries in 'apt' seems to keep hitting it and work

I got this 

 `echo 'APT::Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries`

from [here](https://askubuntu.com/questions/875213/apt-get-to-retry-downloading) setting this as a RUN command before using apt seems to work.

**Comment by cswgr** [comment]
Thanks, but it doesn't work on my machine.

**Comment by genotrance** [comment]
I've made some minor tweaks and no longer see any 444s with apt as mentioned in #113. I'm not able to test docker-compose so any testing with the latest px will be appreciated.

**Comment by eitsupi** [comment]
In the case of Docker Desktop, you can write the proxy address as `http://host.docker.internal:3128` in `~/.docker/config.json` without any problem.

Sorry for the Japanese article, but I am using px with this setting. Thanks for the great work.
https://qiita.com/eitsupi/items/226b65d54e207a7c5fe7#docker-desktopwsl2%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E3%81%AElinux%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A
