### ISSUE TITLE
Python 10, import order fix

### ISSUE THREAD

**Issue by JKE96** [genotrance/px#122]
I noticed on python 3.10 if you import sspi before pywintypes in the px.py that it looks like it works.

```
PS C:\Users\user.name> py -m px
Requires module pywin32
```

```
PS C:\Users\user.name> py
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywintypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user.name\AppData\Roaming\Python\Python310\site-packages\win32\lib\pywintypes.py", line 117, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\user.name\AppData\Roaming\Python\Python310\site-packages\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes310.dll)
>>> import sspi
>>> import pywintypes
>>>
```

```
#try:
#    import pywintypes
#    import sspi
#except ImportError:
#    pprint("Requires module pywin32")
#    sys.exit()
try:
    import sspi
except ImportError:
    pprint("Requires module pywin32 sspi")
    sys.exit()
try:
    import pywintypes
except ImportError:
    pprint("Requires module pywin32 pywintypes")
    sys.exit()
```

```
PS C:\Users\user.name> py -m px
Serving at - proc MainProcess
Serving at - proc Process-1
```

**Comment by genotrance** [comment]
Thanks for the report and PR.
