### ISSUE TITLE
SyntaxError when calling px.py

### ISSUE THREAD

**Issue by bensch98** [genotrance/px#125]
I just installed px and wanted to explore the CLI like this:
```powershell
python px.py
```

But I get an invalid SyntaxError:
```text
Traceback (most recent call last):
  File "C:\Users\BENSCH98\AppData\Roaming\Python\Python39\site-packages\px.py", line 29, in <module>
    import concurrent.futures
  File "C:\Users\BENSCH98\AppData\Roaming\Python\Python39\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Users\BENSCH98\AppData\Roaming\Python\Python39\site-packages\concurrent\futures\_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

**Comment by genotrance** [comment]
Looks like [others ](https://github.com/boto/boto3/issues/1399)have seen this as well.

**Comment by bensch98** [comment]
See link above
