### ISSUE TITLE
"LookupError: unknown encoding: idna" with binary release

### ISSUE THREAD

**Issue by adolfocorreia** [genotrance/px#134]
First of all, kudos for this amazing project!

With the new release (v0.5.1), I now get an encoding error when using the binary version of px. I tried reproducing the error using the python version, but it is working fine for me, so I guess the error has something to do with the binary creation process.

I found some reports of similar problems on the Internet suggesting adding ```import encodings.idna``` but I don't if it is relevant here. This might be relevant though: https://stackoverflow.com/questions/42910325/unknown-encoding-idna-when-using-the-requests-library-with-nuitka

Here is the error log:

```
Serving at :3128 proc MainProcess
MainProcess: MainThread: 1648127339: detach_console: Freed console successfully
MainProcess: MainThread: 1648127339: print_banner: proxy:server = XXXXX.XXXXX:8080
MainProcess: MainThread: 1648127339: print_banner: proxy:pac =
MainProcess: MainThread: 1648127339: print_banner: proxy:listen =
MainProcess: MainThread: 1648127339: print_banner: proxy:port = 3128
MainProcess: MainThread: 1648127339: print_banner: proxy:gateway = 0
MainProcess: MainThread: 1648127339: print_banner: proxy:hostonly = 1
MainProcess: MainThread: 1648127339: print_banner: proxy:allow =
MainProcess: MainThread: 1648127339: print_banner: proxy:noproxy = 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
MainProcess: MainThread: 1648127339: print_banner: proxy:useragent =
MainProcess: MainThread: 1648127339: print_banner: proxy:username =
MainProcess: MainThread: 1648127339: print_banner: proxy:auth =
MainProcess: MainThread: 1648127339: print_banner: settings:workers = 2
MainProcess: MainThread: 1648127339: print_banner: settings:threads = 5
MainProcess: MainThread: 1648127339: print_banner: settings:idle = 30
MainProcess: MainThread: 1648127339: print_banner: settings:socktimeout = 20.0
MainProcess: MainThread: 1648127339: print_banner: settings:proxyreload = 60
MainProcess: MainThread: 1648127339: print_banner: settings:foreground = 0
MainProcess: MainThread: 1648127339: print_banner: settings:log = 1
MainProcess: MainThread: 1648127360: verify_request: Client address: 127.0.0.1

Traceback (most recent call last):
  File "C:\XXXXX\px.py", line 1943, in <module>
  File "C:\XXXXX\px.py", line 1940, in main
  File "C:\XXXXX\px.py", line 1227, in run_pool
  File "C:\XXXXX\px.py", line 1182, in serve_forever
  File "C:\XXXXX\socketserver.py", line 237, in serve_forever
  File "C:\XXXXX\socketserver.py", line 314, in _handle_request_noblock
  File "C:\XXXXX\px.py", line 1138, in verify_request
  File "C:\XXXXX\px.py", line 1123, in get_host_ips
  File "C:\XXXXX\socket.py", line 955, in getaddrinfo
LookupError: unknown encoding: idna
```

**Comment by genotrance** [comment]
I just updated the binary - please retry and let me know how it works.

https://github.com/genotrance/px/releases/tag/v0.5.1

**Comment by adolfocorreia** [comment]
Thank you, I don't get the encoding error anymore! I'll test it in the next days and report back if anything else comes up.
