### ISSUE TITLE
self.path not getting filled properly

### ISSUE THREAD

**Issue by ggimenes** [genotrance/px#138]
I'm trying to run a very basic example and getting the following error:

Command:
`px --proxy=proxyserver.com:80 --debug`

Error:

```
C:\Windows\system32>px --proxy=proxyserver.com:80 --debug
MainProcess: MainThread: 1649343527: __init__: Proxy mode =MODE_CONFIG
Serving at 127.0.0.1:3128 proc MainProcess
MainProcess: MainThread: 1649343527: print_banner: proxy:server = proxyserver.com:80
MainProcess: MainThread: 1649343527: print_banner: proxy:pac =
MainProcess: MainThread: 1649343527: print_banner: proxy:port = 3128
MainProcess: MainThread: 1649343527: print_banner: proxy:listen = 127.0.0.1
MainProcess: MainThread: 1649343527: print_banner: proxy:allow = *.*.*.*
MainProcess: MainThread: 1649343527: print_banner: proxy:gateway = 0
MainProcess: MainThread: 1649343527: print_banner: proxy:hostonly = 0
MainProcess: MainThread: 1649343527: print_banner: proxy:noproxy =
MainProcess: MainThread: 1649343527: print_banner: proxy:useragent =
MainProcess: MainThread: 1649343527: print_banner: proxy:username =
MainProcess: MainThread: 1649343527: print_banner: proxy:auth =
MainProcess: MainThread: 1649343527: print_banner: settings:workers = 2
MainProcess: MainThread: 1649343527: print_banner: settings:threads = 5
MainProcess: MainThread: 1649343527: print_banner: settings:idle = 30
MainProcess: MainThread: 1649343527: print_banner: settings:socktimeout = 20.0
MainProcess: MainThread: 1649343527: print_banner: settings:proxyreload = 60
MainProcess: MainThread: 1649343527: print_banner: settings:foreground = 0
MainProcess: MainThread: 1649343527: print_banner: settings:log = 1
Process-1: MainThread: 1649343527: __init__: Proxy mode =MODE_CONFIG
Serving at 127.0.0.1:3128 proc Process-1
Process-1: MainThread: 1649343527: print_banner: proxy:server = proxyserver.com:80
Process-1: MainThread: 1649343527: print_banner: proxy:pac =
Process-1: MainThread: 1649343527: print_banner: proxy:port = 3128
Process-1: MainThread: 1649343527: print_banner: proxy:listen = 127.0.0.1
Process-1: MainThread: 1649343527: print_banner: proxy:allow = *.*.*.*
Process-1: MainThread: 1649343528: print_banner: proxy:gateway = 0
Process-1: MainThread: 1649343528: print_banner: proxy:hostonly = 0
Process-1: MainThread: 1649343528: print_banner: proxy:noproxy =
Process-1: MainThread: 1649343528: print_banner: proxy:useragent =
Process-1: MainThread: 1649343528: print_banner: proxy:username =
Process-1: MainThread: 1649343528: print_banner: proxy:auth =
Process-1: MainThread: 1649343528: print_banner: settings:workers = 2
Process-1: MainThread: 1649343528: print_banner: settings:threads = 5
Process-1: MainThread: 1649343528: print_banner: settings:idle = 30
Process-1: MainThread: 1649343528: print_banner: settings:socktimeout = 20.0
Process-1: MainThread: 1649343528: print_banner: settings:proxyreload = 60
Process-1: MainThread: 1649343528: print_banner: settings:foreground = 0
Process-1: MainThread: 1649343528: print_banner: settings:log = 1
MainProcess: MainThread: 1649343544: verify_request: Client address: 127.0.0.1
MainProcess: Thread_0: 1649343544: do_GET: Entering
MainProcess: Thread_0: 1649343544: do_GET: Path = /
MainProcess: Thread_0: 1649343544: do_transaction: Entering
https:///
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 58211)
Traceback (most recent call last):
  File "C:\Python310\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python310\lib\http\server.py", line 651, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Python310\lib\site-packages\px.py", line 450, in handle_one_request
    httpserver.SimpleHTTPRequestHandler.handle_one_request(self)
  File "C:\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Python310\lib\site-packages\px.py", line 795, in do_GET
    resp = self.do_transaction()
  File "C:\Python310\lib\site-packages\px.py", line 681, in do_transaction
    ipport = self.get_destination()
  File "C:\Python310\lib\site-packages\px.py", line 1030, in get_destination
    servers, netloc, path = State.wproxy.find_proxy_for_url(
  File "C:\Python310\lib\site-packages\wproxy.py", line 439, in find_proxy_for_url
    servers, netloc, path = super().find_proxy_for_url(url)
  File "C:\Python310\lib\site-packages\wproxy.py", line 214, in find_proxy_for_url
    netloc, path = self.get_netloc(url)
  File "C:\Python310\lib\site-packages\wproxy.py", line 161, in get_netloc
    netloc = (spl[0], int(spl[1]))
ValueError: invalid literal for int() with base 10: '///'
----------------------------------------
MainProcess: MainThread: 1649343545: verify_request: Client address: 127.0.0.1
MainProcess: Thread_0: 1649343545: do_GET: Entering
MainProcess: Thread_0: 1649343545: do_GET: Path = /
MainProcess: Thread_0: 1649343545: do_transaction: Entering
https:///
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 58212)
Traceback (most recent call last):
  File "C:\Python310\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python310\lib\http\server.py", line 651, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Python310\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Python310\lib\site-packages\px.py", line 450, in handle_one_request
    httpserver.SimpleHTTPRequestHandler.handle_one_request(self)
  File "C:\Python310\lib\http\server.py", line 413, in handle_one_request
    method()
  File "C:\Python310\lib\site-packages\px.py", line 795, in do_GET
    resp = self.do_transaction()
  File "C:\Python310\lib\site-packages\px.py", line 681, in do_transaction
    ipport = self.get_destination()
  File "C:\Python310\lib\site-packages\px.py", line 1030, in get_destination
    servers, netloc, path = State.wproxy.find_proxy_for_url(
  File "C:\Python310\lib\site-packages\wproxy.py", line 439, in find_proxy_for_url
    servers, netloc, path = super().find_proxy_for_url(url)
  File "C:\Python310\lib\site-packages\wproxy.py", line 214, in find_proxy_for_url
    netloc, path = self.get_netloc(url)
  File "C:\Python310\lib\site-packages\wproxy.py", line 161, in get_netloc
    netloc = (spl[0], int(spl[1]))
ValueError: invalid literal for int() with base 10: '///'
```

As we can see, the path printed is: MainProcess: Thread_0: 1649343545: do_GET: Path = /
And I also put a print into the wproxy.py file, at the beginning of the "find_proxy_for_url",  to understand what is going on. It's right after the line "MainProcess: Thread_0: 1649343545: do_transaction: Entering" and is printing "https:///"

Python version 3.10.4
Windows Server 2016 Datacenter

**Comment by genotrance** [comment]
Thanks for the report - what's the actual URL you are requesting via the client? Is it HTTP or HTTPS? GET/POST/etc. will help.
