### ISSUE TITLE
0.7.0: [Errno 10054] An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by henkwiedig** [genotrance/px#148]
The new 0.7.0 does have the following error for me.
0.6.3 works fine.
```
MainProcess: MainThread: 1652886016: /main/parse_config/attach_console: Already attached to a console
MainProcess: MainThread: 1652886016: /main/parse_config/__init__: AutoConfigURL = http://proxy.interna:3132/proxy.pac
MainProcess: MainThread: 1652886016: /main/parse_config/__init__: Proxy mode = MODE_PAC
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: libcurl/7.82.0 OpenSSL/3.0.2 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 libgsasl/1.10.0
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_SSL: True
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_SSPI: True
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_SPNEGO: True
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_GSSAPI: False
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_GSSNEGOTIATE: False
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_KERBEROS5: True
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_NTLM: True
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: CURL_VERSION_NTLM_WB: False
MainProcess: MainThread: 1652886016: /parse_config/__init__/curl_version: Host: x86_64-pc-win32
Serving at :7680 proc MainProcess
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:server =
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:pac =
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:listen =
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:port = 7680
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:gateway = 1
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:hostonly = 0
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:allow = 127.0.0.1,172.*.*.*,192.168.*.*
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:noproxy =
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:useragent =
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:username =
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: proxy:auth =
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: settings:workers = 2
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: settings:threads = 5
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: settings:idle = 30
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: settings:socktimeout = 20.0
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: settings:proxyreload = 60
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: settings:foreground = 1
MainProcess: MainThread: 1652886016: /main/run_pool/print_banner: settings:log = 0
Process-1: MainThread: 1652886017: /start_worker/parse_config/attach_console: Already attached to a console
Process-1: MainThread: 1652886017: /start_worker/parse_config/__init__: AutoConfigURL = http://proxy.interna:3132/proxy.pac
Process-1: MainThread: 1652886017: /start_worker/parse_config/__init__: Proxy mode = MODE_PAC
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: libcurl/7.82.0 OpenSSL/3.0.2 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 libgsasl/1.10.0
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_SSL: True
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_SSPI: True
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_SPNEGO: True
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_GSSAPI: False
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_GSSNEGOTIATE: False
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_KERBEROS5: True
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_NTLM: True
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: CURL_VERSION_NTLM_WB: False
Process-1: MainThread: 1652886017: /parse_config/__init__/curl_version: Host: x86_64-pc-win32
Serving at :7680 proc Process-1
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:server =
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:pac =
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:listen =
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:port = 7680
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:gateway = 1
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:hostonly = 0
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:allow = 127.0.0.1,172.*.*.*,192.168.*.*
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:noproxy =
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:useragent =
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:username =
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: proxy:auth =
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: settings:workers = 2
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: settings:threads = 5
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: settings:idle = 30
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: settings:socktimeout = 20.0
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: settings:proxyreload = 60
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: settings:foreground = 1
Process-1: MainThread: 1652886017: /run/start_worker/print_banner: settings:log = 0
Process-1: MainThread: 1652886021: /serve_forever/_handle_request_noblock/verify_request: Client address: 172.20.46.183
Process-1: Thread_0: 1652886021: /handle_one_request/do_GET/do_curl: Path = http://www.google.de/
Process-1: Thread_0: 1652886021: /do_GET/do_curl/__init__: b1f833eca382131d3e0762b635531bcf5fe24dbe: New curl instance
Process-1: Thread_0: 1652886021: /do_curl/__init__/_setup: b1f833eca382131d3e0762b635531bcf5fe24dbe: GET http://www.google.de/ using HTTP/1.1
Process-1: Thread_0: 1652886021: /do_curl/get_destination/reload_proxy: Skip proxy refresh
Process-1: Thread_0: 1652886021: /find_proxy_for_url/find_proxy_for_url/get_netloc: netloc = ('www.google.de', 80), path = /
Process-1: Thread_0: 1652886021: /do_GET/do_curl/get_destination: Proxy = [('aaa.internal.com', 8080), ('bbb.internal.com', 8080)]
Process-1: Thread_0: 1652886021: /handle_one_request/do_GET/do_curl: Configuring proxy settings
Process-1: Thread_0: 1652886021: /handle_one_request/do_GET/do_curl: Using SSPI to login
Process-1: Thread_0: 1652886021: /do_GET/do_curl/bridge: b1f833eca382131d3e0762b635531bcf5fe24dbe: Setting up bridge
Process-1: Thread_0: 1652886021: /do_GET/do_curl/set_headers: b1f833eca382131d3e0762b635531bcf5fe24dbe: Skipping header =!> Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1652886021: /do_curl/do/add: b1f833eca382131d3e0762b635531bcf5fe24dbe: Handles = 0
Process-1: Thread_0: 1652886021: /do/add/_add_handle: b1f833eca382131d3e0762b635531bcf5fe24dbe: Add handle
Process-1: Thread_0: 1652886021: /do/add/_add_handle: b1f833eca382131d3e0762b635531bcf5fe24dbe: Added handle
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Trying 1.2.3.4:8080...
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Connected to aaa.internal.com (1.2.3.4) port 8080 (#0)
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => GET http://www.google.de/ HTTP/1.1
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => Host: www.google.de
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => User-Agent: curl/7.68.0
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => Accept: */*
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Mark bundle as not supporting multiuse
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= HTTP/1.1 407 authenticationrequired
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Date: Wed, 18 May 2022 15:00:20 GMT
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Content-Type: text/html
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Cache-Control: no-cache
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Content-Length: 4876
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= X-Frame-Options: deny
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Proxy-Authenticate: Negotiate
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Proxy-Authenticate: NTLM
Process-1: Thread_0: 1652886021: /perform/_socket_action/_header_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Done sending headers
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Ignoring the response-body
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Connection #0 to host aaa.internal.com left intact
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Issue another request to this URL: 'http://www.google.de/'
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Found bundle for host aaa.internal.com: 0x233367865f0 [serially]
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Re-using existing connection! (#0) with proxy aaa.internal.com
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Connected to aaa.internal.com (1.2.3.4) port 8080 (#0)
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Proxy auth using Negotiate with user sanitized len(2)
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => GET http://www.google.de/ HTTP/1.1
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => Host: www.google.de
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => Proxy-Authorization: Negotiate sanitized len(3292)
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => User-Agent: curl/7.68.0
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Sent header => Accept: */*
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Mark bundle as not supporting multiuse
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= HTTP/1.1 200 OK
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Date: Wed, 18 May 2022 15:00:20 GMT
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Vary: Accept-Encoding
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Server: gws
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Expires: -1
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= X-Cache: MISS from 1.2.3.4
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Set-Cookie: AEC=fgjjjhhg-gjjhfhf; expires=Mon, 14-Nov-2022 15:00:21 GMT; path=/; domain=.google.de; Secure; HttpOnly; SameSite=lax
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Content-Type: text/html; charset=ISO-8859-1
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Accept-Ranges: none
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Cache-Control: private, max-age=0
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= X-Frame-Options: SAMEORIGIN
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= X-XSS-Protection: 0
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Received header <= Transfer-Encoding: chunked
Process-1: Thread_0: 1652886021: /perform/_socket_action/_header_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Done sending headers
Process-1: Thread_0: 1652886021: /perform/_socket_action/_write_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Wrote 11430 bytes
Process-1: Thread_0: 1652886021: /perform/_socket_action/_write_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Write error: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Failure writing output to destination
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Failed reading the chunked-encoded stream
Process-1: Thread_0: 1652886021: /perform/_socket_action/_debug_callback: b1f833eca382131d3e0762b635531bcf5fe24dbe: Curl info: Closing connection 0
Process-1: Thread_0: 1652886021: /handle_one_request/do_GET/do_curl: Connection failed: 23;
Process-1: Thread_0: 1652886021: /send_error/log_error/log_message: code 503, message 23;
Process-1: Thread_0: 1652886021: /send_response/log_request/log_message: "GET http://www.google.de/ HTTP/1.1" 503 -
Traceback (most recent call last):
  File "C:\TEMP\PX-V07~1.0-W\px\main.py", line 289, in handle_one_request
  File "C:\TEMP\PX-V07~1.0-W\http\server.py", line 413, in handle_one_request
  File "C:\TEMP\PX-V07~1.0-W\px\main.py", line 390, in do_GET
  File "C:\TEMP\PX-V07~1.0-W\px\main.py", line 353, in do_curl
  File "C:\TEMP\PX-V07~1.0-W\http\server.py", line 477, in send_error
  File "C:\TEMP\PX-V07~1.0-W\http\server.py", line 527, in end_headers
  File "C:\TEMP\PX-V07~1.0-W\http\server.py", line 531, in flush_headers
  File "C:\TEMP\PX-V07~1.0-W\socketserver.py", line 826, in write
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
Process-1: Thread_0: 1652886021: /__init__/handle/handle_one_request: Socket error: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
Process-1: Thread_0: 1652886021: /handle_one_request/stop/_remove_handle: b1f833eca382131d3e0762b635531bcf5fe24dbe: Remove handle: 23; Stopped;
```

**Comment by genotrance** [comment]
Can you provide the output of the `curl -v` command line output? Want to see what the client is receiving. It looks like it closes the connection since it didn't like what it got back.

**Comment by henkwiedig** [comment]
Sure
```
$ curl -v www.google.de
* Uses proxy env variable http_proxy == 'http://172.27.48.1:7680'
*   Trying 172.27.48.1:7680...
* TCP_NODELAY set
* Connected to 172.27.48.1 (172.27.48.1) port 7680 (#0)
> GET http://www.google.de/ HTTP/1.1
> Host: www.google.de
> User-Agent: curl/7.68.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 407 authenticationrequired
< Date: Wed, 18 May 2022 22:36:08 GMT
< Content-Type: text/html
< Cache-Control: no-cache
< Content-Length: 4877
< X-Frame-Options: deny
< Proxy-Connection: Keep-Alive
< Proxy-Authenticate: Negotiate
< Proxy-Authenticate: NTLM
<
HTTP/1.1 200 OK
Date: Wed, 18 May 2022 22:36:08 GMT
Vary: Accept-Encoding
Server: gws
Expires: -1
X-Cache: MISS from 10.140.10.13
Set-Cookie: AEC=aasdfsdfc; expires=Mon, 14-Nov-2022 22:36:08 GMT; path=/; domain=.google.de; Secure; HttpOnly; SameSite=lax
Content-Type: text/html; charset=ISO-8859-1
Accept-Ranges: none
Cache-Control: private, max-age=0
X-Frame-Options: SAMEORIGIN
Proxy-Connection: Keep-Alive
X-XSS-Protection: 0
Transfer-Encoding: chunked

3569
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="de"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="59MPekP3ZtxPXxRBVCx_Kw">(function(){window.google={kEI:'2HSFYpi7LIXrsAfg479I',kEXPI:'0,1302536,56873,6059,206,4804,2316,383,246,5,1354,4013,1123753,1578490,16115,28684,17572,4859,1361,284,12028,17587,4020,978,13228,3847,10622,22741,6674,1279,2742,149,1943,1983,3,4311,3514,606,2023,1733,43,521,6345,8325,605,2622,2845,7,17450,16320,4465,13138,1,2,350,230,6178,430,13975,4,1528,2304,7039,25073,2658,4164,3193,924,12734,21223,5824,2533,4092,5,4049,3,3541,1,42154,2,14022,1931,12185,11623,5679,3401,12485,16256,4568,6256,20803,2618,1252,5835,14967,4333,6090,1394,11239,15406,1,436,8155,6582,316,483,12,11760,2908,7341,2650,567,10279,2888,1881,1396,1340,2005,3157,24,878,6683,7928,211,2819,3236,2,2873,3055,2049,699,3153,445,1214,1,3,101,110,2063,133,3571,479,380,91,65,791,1197,1049,97,188,756,442,5417974,5099,71,160,8796585,1326,3,1877,1,2562,1,748,141,801,6158,6751,155,17,13,72,139,4,2,20,2,169,13,19,46,5,39,644,29,2,2,1,2,1,2,2,7,4,1,2,2,2,2,2,2,1052,1,1,158,3,2,2,2,2,2,4,2,3,3,2011,1002,312,615,3,3,3,1,1,1,1,206,1,1,195,12,29,4,2,7,1,5,3,3,3,1,3,6,2,3,1,1,7,1,15,17,20730489,3220020,2738464,1303679,1964,2935,159,1358,12221,3405,307,2298,934292',kBL:'s79p'};google.sn='webhp';google.kHL='de';})();(function(){
var f=this||self;var h,k=[];function l(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return b||h}function m(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b}
function n(a,b,c,d,g){var e="";c||-1!==b.search("&ei=")||(e="&ei="+l(d),-1===b.search("&lei=")&&(d=m(d))&&(e+="&lei="+d));d="";!c&&f._cshid&&-1===b.search("&cshid=")&&"slh"!==a&&(d="&cshid="+f._cshid);c=c||"/"+(g||"gen_204")+"?atyp=i&ct="+a+"&cad="+b+e+"&zx="+Date.now()+d;/^http:/i.test(c)&&"https:"===window.location.protocol&&(google.ml&&google.ml(Error("a"),!1,{src:c,glmm:1}),c="");return c};h=google.kEI;google.getEI=l;google.getLEI=m;google.ml=function(){return null};google.log=function(a,b,c,d,g){if(c=n(a,b,c,d,g)){a=new Image;var e=k.length;k[e]=a;a.onerror=a.onload=a.onabort=function(){delete k[e]};a.src=c}};google.logUrl=n;}).call(this);(function(){
google.y={};google.sy=[];google.x=function(a,b){if(a)var c=a.id;else{do c=Math.random();while(google.y[c])}google.y[c]=[a,b];return!1};google.sx=function(a){google.sy.push(a)};google.lm=[];google.plm=function(a){google.lm.push.apply(google.lm,a)};google.lq=[];google.load=function(a,b,c){google.lq.push([[a],b,c])};google.loadAll=function(a,b){google.lq.push([a,b])};google.bx=!1;google.lx=function(){};}).call(this);google.f={};(function(){
document.documentElement.addEventListener("submit",function(b){var a;if(a=b.target){var c=a.getAttribute("data-submitfalse");a="1"===c||"q"===c&&!a.elements.q.value?!0:!1}else a=!1;a&&(b.preventDefault(),b.stopPropagation())},!0);document.documentElement.addEventListener("click",function(b){var a;a:{for(a=b.target;a&&a!==document.documentElement;a=a.parentElement)if("A"===a.tagName){a="1"===a.getAttribute("data-nohref");break a}a=!1}a&&b.preventDefault()},!0);}).call(this);</script><style>#gbar,#guser{font-size:13px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}
</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#1558d6}em{font-weight:bold;font-style:normal}.lst{height:25px;width:496px}.gsfi,.lst{font:18p* Connection #0 to host 172.27.48.1 left intact
x arial,sans-serif}.gsfs{font:17px arial,sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}body{background:#fff;color:#000}a{color:#4b11a8;text-decoration:none}a:hover,a:active{text-decoration:un $
```

**Comment by genotrance** [comment]
Luckily this is an easy fix - px looks for "Proxy Authentication Required" here:

https://github.com/genotrance/px/blob/92ce257a3b6a39720d765e1d9b12bf4acf2173ed/px/mcurl.py#L155-L158

Your proxy seems to send "HTTP/1.1 407 authenticationrequired" - simple fix. Will make changes and post an update soon.
