### ISSUE TITLE
import problem on macos pip install

### ISSUE THREAD

**Issue by ikamensh** [genotrance/px#157]
I've installed via `pip install px`; my environment:
~ [1] $ python -V                                                                            (base) 14:54:51
Python 3.8.8
MacOS Big Sur 11.6.6

px fails to run any commands with an import problem:
```
~ [1] $ px                                                                                   (base) 14:52:59
Traceback (most recent call last):
  File "/Users/kai7rng/opt/anaconda3/bin/px", line 5, in <module>
    from px.main import main
  File "/Users/kai7rng/opt/anaconda3/lib/python3.8/site-packages/px/main.py", line 82, in <module>
    from . import mcurl
  File "/Users/kai7rng/opt/anaconda3/lib/python3.8/site-packages/px/mcurl.py", line 14, in <module>
    from . import libcurl
  File "/Users/kai7rng/opt/anaconda3/lib/python3.8/site-packages/px/libcurl/__init__.py", line 9, in <module>
    from ._curl import *  # noqa
  File "/Users/kai7rng/opt/anaconda3/lib/python3.8/site-packages/px/libcurl/_curl.py", line 32, in <module>
    from ._platform import CFUNC, defined, from_oid
  File "/Users/kai7rng/opt/anaconda3/lib/python3.8/site-packages/px/libcurl/_platform/__init__.py", line 41, in <module>
    from ._osx     import SOCKET, INVALID_SOCKET, sockaddr, fd_set
ImportError: cannot import name 'SOCKET' from 'px.libcurl._platform._osx' (/Users/kai7rng/opt/anaconda3/lib/python3.8/site-packages/px/libcurl/_platform/_osx/__init__.py)
```

**Comment by genotrance** [comment]
I have a fix for this coming soon - although I'll still claim OSX support is preliminary since I am unable to validate against a real proxy. Also, Px doesn't know how to get proxy settings out of the system configuration yet so will need to be manually configured in px.ini or via environment variables for now.
