### ISSUE TITLE
Px Proxy Issue on Windows

### ISSUE THREAD

**Issue by mailman-2097** [genotrance/px#158]
Having issues in px-proxy which was installed from the full windows release

> Both Windows and Generic credentials added in Control Panel
```
Px
```

# debug logs
[debug-Process-1 (1).log](https://github.com/genotrance/px/files/9116799/debug-Process-1.1.log)
[debug-MainProcess (1).log](https://github.com/genotrance/px/files/9116800/debug-MainProcess.1.log)

> px started as follows
```
px --foreground --debug
```

> environment vars set
```
HTTP_PROXY                     http://localhost:3128
HTTPS_PROXY                    http://localhost:3128
```

```
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:server = xxxx.xxxxx.xxxxxxxx.xxx:40101
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:pac =
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:listen = 127.0.0.1
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:port = 3128
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:gateway = 0
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:hostonly = 0
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:allow = *.*.*.*
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:noproxy =
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:useragent =
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:username = Px
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: proxy:auth =
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: settings:workers = 2
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: settings:threads = 5
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: settings:idle = 30
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: settings:socktimeout = 20.0
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: settings:proxyreload = 60
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: settings:foreground = 1
Process-1: MainThread: 1657603176: /run/start_worker/print_banner: settings:log = 0
MainProcess: MainThread: 1657603264: /serve_forever/_handle_request_noblock/verify_request: Client address: 127.0.0.1
MainProcess: Thread_0: 1657603264: /do_CONNECT/do_curl/__init__: 1dcb838e2129b471a33b074eafc9980f15ccef4b: New curl instance
MainProcess: Thread_0: 1657603264: /do_curl/__init__/_setup: 1dcb838e2129b471a33b074eafc9980f15ccef4b: CONNECT releases.hashicorp.com:443 using HTTP/1.1
MainProcess: Thread_0: 1657603264: /handle_one_request/do_CONNECT/do_curl: 1dcb838e2129b471a33b074eafc9980f15ccef4b: Path = releases.hashicorp.com:443
MainProcess: Thread_0: 1657603264: /find_proxy_for_url/find_proxy_for_url/get_netloc: netloc = ('releases.hashicorp.com', 443), path = /
MainProcess: Thread_0: 1657603264: /do_CONNECT/do_curl/get_destination: 1dcb838e2129b471a33b074eafc9980f15ccef4b: Proxy = [('xxx.xxx.xxx.xxx', xxxx)]
MainProcess: Thread_0: 1657603264: /handle_one_request/do_CONNECT/do_curl: 1dcb838e2129b471a33b074eafc9980f15ccef4b: Configuring proxy settings
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 53678)
Traceback (most recent call last):
  File "C:\Tools\px\socketserver.py", line 683, in process_request_thread
  File "C:\Tools\px\socketserver.py", line 360, in finish_request
  File "C:\Tools\px\socketserver.py", line 747, in __init__
  File "C:\Tools\px\http\server.py", line 425, in handle
  File "C:\Tools\px\px\main.py", line 295, in handle_one_request
  File "C:\Tools\px\http\server.py", line 413, in handle_one_request
  File "C:\Tools\px\px\main.py", line 392, in do_CONNECT
  File "C:\Tools\px\px\main.py", line 340, in do_curl
  File "C:\Tools\px\keyring\core.py", line 55, in get_password
  File "C:\Tools\px\keyring\backends\fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
----------------------------------------
```

Please can you assist..

**Comment by mailman-2097** [comment]
Closing Issue and moving to discussion

**Comment by genotrance** [comment]
This is a valid issue and broken in the Windows binary since v0.7.1! Seems like the majority of Windows binary users rely on SSPI which is why this wasn't reported until now. 

A fix is coming shortly. I'll also be checking the test cases to see why this wasn't caught.

Thanks for the report!

**Comment by mailman-2097** [comment]
Thanks for that.
