### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mbaeuerle** [genotrance/px#223]
I'm getting this error on 0.9.2. on an Intel Mac Sonoma 14.6.1 with Python 3.12.3.
I installed px via pipx.

Whenever I'm trying to push a docker image to a remote repository it is aborted showing `ERROR: EOF`.

The px logs then reveal:
```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50774)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/Users/my-user/.local/pipx/venvs/px-proxy/lib/python3.12/site-packages/px/handler.py", line 128, in handle_one_request
    http.server.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/Users/my-user/.local/pipx/venvs/px-proxy/lib/python3.12/site-packages/px/handler.py", line 248, in do_CONNECT
    self.do_curl()
  File "/Users/my-user/.local/pipx/venvs/px-proxy/lib/python3.12/site-packages/px/handler.py", line 206, in do_curl
    STATE.mcurl.select(self.curl, self.connection, STATE.idle)
  File "/Users/my-user/.local/pipx/venvs/px-proxy/lib/python3.12/site-packages/px/mcurl.py", line 1087, in select
    data = wdata[0]
           ~~~~~^^^
IndexError: list index out of range
----------------------------------------
```

**Comment by genotrance** [comment]
I know it's been a while but will be very helpful to get the full log to fix this correctly. Thanks in advance.

**Comment by genotrance** [comment]
Fixed in pymcurl [v8.12.1.1](https://github.com/genotrance/mcurl/releases/tag/v8.12.1.1).

**Comment by mbaeuerle** [comment]
Thanks, will try it out! Didn't receive notifications therefore noticed only now.
