### ISSUE TITLE
Version after 4a07056 do not work on windows

### ISSUE THREAD

**Issue by magnetik** [genotrance/px#34]
Hi,

Using latest release, on windows, got the error in every request:

```
MainProcess: Thread_0: 1520419833: do_socket: Reading response code
MainProcess: Thread_0: 1520419833: do_socket: Response code: 407 False
MainProcess: Thread_0: 1520419833: do_socket: Reading response headers
MainProcess: Thread_0: 1520419833: do_socket: Received header Via = 1.1 10.0.3.5 (McAfee Web Gateway 7.7.2.7.0.24770)
MainProcess: Thread_0: 1520419833: do_socket: Received header Date = Wed, 07 Mar 2018 10:50:34 GMT
MainProcess: Thread_0: 1520419833: do_socket: Received header Content-Type = text/html
MainProcess: Thread_0: 1520419833: do_socket: Received header Cache-Control = no-cache
MainProcess: Thread_0: 1520419833: do_socket: Received header Content-Length = 3887
MainProcess: Thread_0: 1520419833: do_socket: Received header Proxy-Connection = Keep-Alive
MainProcess: Thread_0: 1520419833: do_socket: Received header Proxy-Authenticate = Negotiate
MainProcess: Thread_0: 1520419833: do_socket: Received header Proxy-Authenticate = NTLM
MainProcess: Thread_0: 1520419833: do_socket: Received header Proxy-Authenticate = Basic realm="Proxy Authentication"
MainProcess: Thread_0: 1520419833: do_socket: Reading response data
MainProcess: Thread_0: 1520419833: do_socket: Content length 3887
MainProcess: Thread_0: 1520419833: do_transaction: Auth required
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59105)
Traceback (most recent call last):
  File "socketserver.py", line 639, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "socketserver.py", line 696, in __init__
  File "http\server.py", line 418, in handle
  File "px.py", line 275, in handle_one_request
  File "http\server.py", line 406, in handle_one_request
  File "px.py", line 614, in do_GET
  File "px.py", line 551, in do_transaction
IndexError: list index out of range
```

**Comment by genotrance** [comment]
Can you please send the entire log from startup? Do you know was the previous release that worked for you?

**Comment by magnetik** [comment]
8ac5f4f is not working either, v0.3 is working fine. I won't be able to post full logs until tomorrow :)

**Comment by magnetik** [comment]
Using `4a07056`, full log : [debug-MainProcess.log](https://github.com/genotrance/px/files/1792248/debug-MainProcess.log)

**Comment by genotrance** [comment]
For some reason, your proxy doesn't like the auth generated by WinKerberos which I moved to after 0.3.0 since pywin32 SSPI didn't work with Kerberos.

Can you please run the attached script and see if the strings you get from WinKerberos matches pywin32? If you don't have Python, I can send you a build instead.

[ntlm-test.zip](https://github.com/genotrance/px/files/1798495/ntlm-test.zip)

**Comment by magnetik** [comment]
I do not have a working python version. Can you build one with logs?

Using latest build 44c708f I've:
```
Process-1: Thread_0: 1521185011: do_transaction: Auth required
Process-1: Thread_0: 1521185011: do_transaction: Didn't get challenge, auth didn't work
```

**Comment by magnetik** [comment]
Latest build `ca5d1fb` have the same problem here.

**Comment by geekonthepc** [comment]
```
MainProcess: Thread_0: 1523633983: do_socket: Entering
MainProcess: Thread_0: 1523633983: do_socket: CONNECT update.filezilla-project.org:443 HTTP/1.1
MainProcess: Thread_0: 1523633983: do_socket: Sending host: update.filezilla-project.org:443
MainProcess: Thread_0: 1523633983: do_socket: Sending user-agent: FileZilla/3.32.0
MainProcess: Thread_0: 1523633983: do_socket: Sending extra Proxy-Authorization: sanitized len(1450)
MainProcess: Thread_0: 1523633983: do_socket: Reading response code
MainProcess: Thread_0: 1523633983: do_socket: Response code: 407 False
MainProcess: Thread_0: 1523633983: do_socket: Reading response headers
MainProcess: Thread_0: 1523633983: do_socket: Received Server: Zscaler/6.0
MainProcess: Thread_0: 1523633983: do_socket: Received Cache-control: no-cache
MainProcess: Thread_0: 1523633983: do_socket: Received Content-Length: 0
MainProcess: Thread_0: 1523633983: do_socket: Received Proxy-Authenticate: sanitized (9)
MainProcess: Thread_0: 1523633983: do_socket: Reading response data
MainProcess: Thread_0: 1523633983: do_transaction: Auth required
MainProcess: Thread_0: 1523633983: do_transaction: Didn't get challenge, auth didn't work
MainProcess: Thread_0: 1523633983: do_CONNECT: Error 407
MainProcess: Thread_0: 1523633983: log_message: code 407, message Proxy Authentication Required
MainProcess: Thread_0: 1523633983: log_message: "CONNECT update.filezilla-project.org:443 HTTP/1.1" 407 -
MainProcess: Thread_0: 1523633983: do_CONNECT: Transferred 0 bytes
MainProcess: Thread_0: 1523633983: do_CONNECT: Done

```

Getting the same I think with ca5d1fb as well.

**Comment by genotrance** [comment]
Okay this has gone on long enough, I brought back pywin32 to manage NTLM auth and winkerberos can do Kerberos. This should fix this issue once and for all.

Please try this out and confirm if it works.

**Comment by magnetik** [comment]
Testing latest and it's working. Thanks!
