### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by henkwiedig** [genotrance/px#47]
I'm having issues with large files

Process-1: Thread_1: 1524733960: do_socket: Reading response headers
Process-1: Thread_1: 1524733960: do_socket: Received Server: Apache
Process-1: Thread_1: 1524733960: do_socket: Received Accept-Ranges: bytes
Process-1: Thread_1: 1524733960: do_socket: Received Content-Type: application/zip
Process-1: Thread_1: 1524733960: do_socket: Received Last-Modified: Fri, 26 Jan 2018 07:39:56 GMT
Process-1: Thread_1: 1524733960: do_socket: Received Content-Length: 3814407425
Process-1: Thread_1: 1524733960: do_socket: Received Date: Thu, 26 Apr 2018 09:12:40 GMT
Process-1: Thread_1: 1524733960: do_socket: Received Connection: close
Process-1: Thread_1: 1524733961: do_socket: Received Age: 0
Process-1: Thread_1: 1524733961: do_socket: Reading response data
Process-1: Thread_1: 1524733961: do_socket: Content length 3814407425
----------------------------------------
Exception happened during processing of request from ('10.0.0.3', 52351)
Traceback (most recent call last):
  File "socketserver.py", line 639, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "socketserver.py", line 696, in __init__
  File "http\server.py", line 418, in handle
  File "px.py", line 288, in handle_one_request
  File "http\server.py", line 406, in handle_one_request
  File "px.py", line 635, in do_GET
  File "px.py", line 584, in do_transaction
  File "px.py", line 471, in do_socket
OverflowError: cannot fit 'int' into an index-sized integer
----------------------------------------

**Comment by henkwiedig** [comment]
The Issue occurs on the binary build "px.exe"  on ca5d1fb.
Using source and Miniconda3 x64 the px.py seems to download the file to main memory which is maybe a bug by itelf

**Comment by genotrance** [comment]
Are you seeing the exception on Python 2 or 3? 

I agree loading into memory is wrong but am wondering if it's worth fixing if everyone is moving to https.

**Comment by henkwiedig** [comment]
I dont' know what version of python the binary build includes.
At least python 3 works !

**Comment by henkwiedig** [comment]
As to "loading into memory": isn't it the same with https ? The response is buffered to memory before sending back to client.

**Comment by genotrance** [comment]
This has been fixed in latest release posted. Please verify that it works as expected now.
