### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by henkwiedig** [genotrance/px#60]
On new Px v0.4.0 i see the following:

```Process-1: MainThread: 1534233940: attach_console: Attaching to console 13948
Serving at :3128 proc Process-1
Process-1: MainThread: 1534233940: print_banner: proxy:server = proxy-host:8080
Process-1: MainThread: 1534233940: print_banner: proxy:port = 3128
Process-1: MainThread: 1534233940: print_banner: proxy:listen = 
Process-1: MainThread: 1534233940: print_banner: proxy:allow = *.*.*.*
Process-1: MainThread: 1534233940: print_banner: proxy:gateway = 1
Process-1: MainThread: 1534233940: print_banner: proxy:hostonly = 0
Process-1: MainThread: 1534233940: print_banner: proxy:noproxy = 
Process-1: MainThread: 1534233940: print_banner: proxy:useragent = 
Process-1: MainThread: 1534233940: print_banner: settings:workers = 2
Process-1: MainThread: 1534233940: print_banner: settings:threads = 5
Process-1: MainThread: 1534233940: print_banner: settings:idle = 30
Process-1: MainThread: 1534233940: print_banner: settings:socktimeout = 30.0
Process-1: MainThread: 1534233940: print_banner: settings:proxyreload = 60
Process-1: MainThread: 1534233940: print_banner: settings:foreground = 1
Process-1: MainThread: 1534233940: print_banner: settings:log = 1
Process-1: MainThread: 1534233948: verify_request: Client address: 127.0.0.1
Process-1: Thread_0: 1534233948: do_GET: Entering
Process-1: Thread_0: 1534233948: do_GET: Path = http://www.google.de/
Process-1: Thread_0: 1534233948: do_transaction: Entering
Process-1: Thread_0: 1534233948: get_destination: www.google.de:80
Process-1: Thread_0: 1534233948: do_socket_connect: New connection: ('proxy-host', 8080)
Process-1: Thread_0: 1534233948: do_proxy_type: Searching proxy type
Process-1: Thread_0: 1534233948: do_socket: Entering
Process-1: Thread_0: 1534233948: do_socket: GET http://www.google.de/ HTTP/1.1
Process-1: Thread_0: 1534233948: do_socket: Sending User-Agent: Wget/1.19.1 (cygwin)
Process-1: Thread_0: 1534233948: do_socket: Sending Accept: */*
Process-1: Thread_0: 1534233948: do_socket: Sending Accept-Encoding: identity
Process-1: Thread_0: 1534233948: do_socket: Sending Host: www.google.de
Process-1: Thread_0: 1534233948: do_socket: Sending Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Sending Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Reading response code
Process-1: Thread_0: 1534233948: do_socket: Response code: 407 True
Process-1: Thread_0: 1534233948: do_socket: Reading response headers
Process-1: Thread_0: 1534233948: do_socket: Received Proxy-Authenticate: sanitized (9)
Process-1: Thread_0: 1534233948: do_socket: Received Proxy-Authenticate: sanitized (4)
Process-1: Thread_0: 1534233948: do_socket: Received Cache-Control: no-cache
Process-1: Thread_0: 1534233948: do_socket: Received Pragma: no-cache
Process-1: Thread_0: 1534233948: do_socket: Received Content-Type: text/html; charset=utf-8
Process-1: Thread_0: 1534233948: do_socket: Received Proxy-Connection: close
Process-1: Thread_0: 1534233948: do_socket: Received Set-Cookie: BCSI-CS-96e0d1966dd05766=2; Path=/
Process-1: Thread_0: 1534233948: do_socket: Received Connection: close
Process-1: Thread_0: 1534233948: do_socket: Received Content-Length: 849
Process-1: Thread_0: 1534233948: do_proxy_type: Auth mechanisms: NEGOTIATE NTLM 
Process-1: Thread_0: 1534233948: do_proxy_type: Selected: ('proxy-host', 8080): NTLM
Process-1: Thread_0: 1534233948: get_response_sspi: pywin32 SSPI
Process-1: Thread_0: 1534233948: fwd_data: Reading response data
Process-1: Thread_0: 1534233948: fwd_data: Content length 849
Process-1: Thread_0: 1534233948: fwd_data: Close proxy connection per header
Process-1: Thread_0: 1534233948: do_socket: Entering
Process-1: Thread_0: 1534233948: do_socket_connect: New connection: ('proxy-host', 8080)
Process-1: Thread_0: 1534233948: do_socket: GET http://www.google.de/ HTTP/1.1
Process-1: Thread_0: 1534233948: do_socket: Sending User-Agent: Wget/1.19.1 (cygwin)
Process-1: Thread_0: 1534233948: do_socket: Sending Accept: */*
Process-1: Thread_0: 1534233948: do_socket: Sending Accept-Encoding: identity
Process-1: Thread_0: 1534233948: do_socket: Sending Host: www.google.de
Process-1: Thread_0: 1534233948: do_socket: Sending Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Sending Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Sending extra Proxy-Authorization: sanitized len(77)
Process-1: Thread_0: 1534233948: do_socket: Reading response code
Process-1: Thread_0: 1534233948: do_socket: Response code: 407 True
Process-1: Thread_0: 1534233948: do_socket: Reading response headers
Process-1: Thread_0: 1534233948: do_socket: Received Proxy-Authenticate: sanitized (377)
Process-1: Thread_0: 1534233948: do_socket: Received Cache-Control: no-cache
Process-1: Thread_0: 1534233948: do_socket: Received Pragma: no-cache
Process-1: Thread_0: 1534233948: do_socket: Received Content-Type: text/html; charset=utf-8
Process-1: Thread_0: 1534233948: do_socket: Received Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Received Set-Cookie: BCSI-CS-96e0d1966dd05766=2; Path=/
Process-1: Thread_0: 1534233948: do_socket: Received Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Received Content-Length: 866
Process-1: Thread_0: 1534233948: do_transaction: Auth required
Process-1: Thread_0: 1534233948: do_transaction: Challenged
Process-1: Thread_0: 1534233948: get_response_sspi: pywin32 SSPI
Process-1: Thread_0: 1534233948: fwd_data: Reading response data
Process-1: Thread_0: 1534233948: fwd_data: Content length 866
Process-1: Thread_0: 1534233948: do_socket: Entering
Process-1: Thread_0: 1534233948: do_socket: GET http://www.google.de/ HTTP/1.1
Process-1: Thread_0: 1534233948: do_socket: Sending User-Agent: Wget/1.19.1 (cygwin)
Process-1: Thread_0: 1534233948: do_socket: Sending Accept: */*
Process-1: Thread_0: 1534233948: do_socket: Sending Accept-Encoding: identity
Process-1: Thread_0: 1534233948: do_socket: Sending Host: www.google.de
Process-1: Thread_0: 1534233948: do_socket: Sending Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Sending Proxy-Connection: Keep-Alive
Process-1: Thread_0: 1534233948: do_socket: Sending extra Proxy-Authorization: sanitized len(673)
Process-1: Thread_0: 1534233948: do_socket: Reading response code
Process-1: Thread_0: 1534233948: do_socket: Response code: 200 True
Process-1: Thread_0: 1534233948: do_socket: Reading response headers
Process-1: Thread_0: 1534233948: do_socket: Received Date: Tue, 14 Aug 2018 08:05:48 GMT
Process-1: Thread_0: 1534233948: do_socket: Received Expires: -1
Process-1: Thread_0: 1534233948: do_socket: Received Cache-Control: private, max-age=0
Process-1: Thread_0: 1534233948: do_socket: Received Content-Type: text/html; charset=ISO-8859-1
Process-1: Thread_0: 1534233948: do_socket: Received P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Process-1: Thread_0: 1534233948: do_socket: Received Server: gws
Process-1: Thread_0: 1534233948: do_socket: Received X-XSS-Protection: 1; mode=block
Process-1: Thread_0: 1534233948: do_socket: Received X-Frame-Options: SAMEORIGIN
Process-1: Thread_0: 1534233948: do_socket: Received Accept-Ranges: none
Process-1: Thread_0: 1534233948: do_socket: Received Vary: Accept-Encoding
Process-1: Thread_0: 1534233949: do_socket: Received Transfer-Encoding: chunked
Process-1: Thread_0: 1534233949: do_socket: Received Connection: Keep-Alive
Process-1: Thread_0: 1534233949: do_socket: Received Set-Cookie: 1P_JAR=2018-08-14-08; expires=Thu, 13-Sep-2018 08:05:48 GMT; path=/; domain=.google.de
Process-1: Thread_0: 1534233949: do_socket: Received Set-Cookie: NID=136=XrkyTq68ySPcaQPazFa43AUzFyJKdbs9gATahrZIk9F6n8NoXK5DRAKg9AXU81lGR8AJ1HRAQsVMBF4lgyUd6SiZCS1_nIIxr2JyRV2oGmnfSlDE48915zys-Kr8SUuO; expires=Wed, 13-Feb-2019 08:05:48 GMT; path=/; domain=.google.de; HttpOnly
Process-1: Thread_0: 1534233949: do_socket: Received Age: 0
Process-1: Thread_0: 1534233949: fwd_resp: Entering
Process-1: Thread_0: 1534233949: log_message: "GET http://www.google.de/ HTTP/1.1" 200 -
Process-1: Thread_0: 1534233949: fwd_resp: Returning Date: Tue, 14 Aug 2018 08:05:48 GMT
Process-1: Thread_0: 1534233949: fwd_resp: Returning Expires: -1
Process-1: Thread_0: 1534233949: fwd_resp: Returning Cache-Control: private, max-age=0
Process-1: Thread_0: 1534233949: fwd_resp: Returning Content-Type: text/html; charset=ISO-8859-1
Process-1: Thread_0: 1534233949: fwd_resp: Returning P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Process-1: Thread_0: 1534233949: fwd_resp: Returning Server: gws
Process-1: Thread_0: 1534233949: fwd_resp: Returning X-XSS-Protection: 1; mode=block
Process-1: Thread_0: 1534233949: fwd_resp: Returning X-Frame-Options: SAMEORIGIN
Process-1: Thread_0: 1534233949: fwd_resp: Returning Accept-Ranges: none
Process-1: Thread_0: 1534233949: fwd_resp: Returning Vary: Accept-Encoding
Process-1: Thread_0: 1534233949: fwd_resp: Returning Transfer-Encoding: chunked
Process-1: Thread_0: 1534233949: fwd_resp: Returning Connection: Keep-Alive
Process-1: Thread_0: 1534233949: fwd_resp: Returning Set-Cookie: 1P_JAR=2018-08-14-08; expires=Thu, 13-Sep-2018 08:05:48 GMT; path=/; domain=.google.de
Process-1: Thread_0: 1534233949: fwd_resp: Returning Set-Cookie: NID=136=XrkyTq68ySPcaQPazFa43AUzFyJKdbs9gATahrZIk9F6n8NoXK5DRAKg9AXU81lGR8AJ1HRAQsVMBF4lgyUd6SiZCS1_nIIxr2JyRV2oGmnfSlDE48915zys-Kr8SUuO; expires=Wed, 13-Feb-2019 08:05:48 GMT; path=/; domain=.google.de; HttpOnly
Process-1: Thread_0: 1534233949: fwd_resp: Returning Age: 0
Process-1: Thread_0: 1534233949: fwd_data: Reading response data
Process-1: Thread_0: 1534233949: fwd_data: Chunked encoding
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54888)
Traceback (most recent call last):
  File "socketserver.py", line 639, in process_request_thread
  File "socketserver.py", line 361, in finish_request
  File "socketserver.py", line 696, in __init__
  File "http\server.py", line 418, in handle
  File "px.py", line 355, in handle_one_request
  File "http\server.py", line 406, in handle_one_request
  File "px.py", line 686, in do_GET
  File "px.py", line 894, in fwd_resp
  File "px.py", line 850, in fwd_data
  File "socketserver.py", line 775, in write
TypeError: a bytes-like object is required, not 'str'
----------------------------------------```

**Comment by genotrance** [comment]
Just posted a fix for this in latest release, please verify that it works as expected now. Thanks for reporting!

**Comment by henkwiedig** [comment]
fixed !
